version: "2"

services:
  web:
    build: "."
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
      - "/app/webpack/"
      - "/app/static/"
      - "/app/media/"
      - "./data:/data:rw"
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
    volumes:
      - ".:/app:rw"

  redis:
    image: library/redis:5.0-alpine
    volumes:
      - saleor-redis:/data

  celery:
    build: "."
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    env_file: .env-local
    depends_on:
      - redis

volumes:
  saleor-redis:
    driver: local
